/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as PlayRouteImport } from './routes/play'
import { Route as CamRouteImport } from './routes/cam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesYogaRouteImport } from './routes/games.yoga'
import { Route as GamesSimonRouteImport } from './routes/games.simon'
import { Route as GamesShapesRouteImport } from './routes/games.shapes'
import { Route as GamesScavengerRouteImport } from './routes/games.scavenger'
import { Route as GamesRoutineRouteImport } from './routes/games.routine'
import { Route as GamesFreezeRouteImport } from './routes/games.freeze'
import { Route as GamesColorsRouteImport } from './routes/games.colors'
import { Route as GamesAnimalsRouteImport } from './routes/games.animals'
import { Route as GamesAlphabetRouteImport } from './routes/games.alphabet'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const CamRoute = CamRouteImport.update({
  id: '/cam',
  path: '/cam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesYogaRoute = GamesYogaRouteImport.update({
  id: '/games/yoga',
  path: '/games/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSimonRoute = GamesSimonRouteImport.update({
  id: '/games/simon',
  path: '/games/simon',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesShapesRoute = GamesShapesRouteImport.update({
  id: '/games/shapes',
  path: '/games/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesScavengerRoute = GamesScavengerRouteImport.update({
  id: '/games/scavenger',
  path: '/games/scavenger',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoutineRoute = GamesRoutineRouteImport.update({
  id: '/games/routine',
  path: '/games/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFreezeRoute = GamesFreezeRouteImport.update({
  id: '/games/freeze',
  path: '/games/freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesColorsRoute = GamesColorsRouteImport.update({
  id: '/games/colors',
  path: '/games/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAnimalsRoute = GamesAnimalsRouteImport.update({
  id: '/games/animals',
  path: '/games/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAlphabetRoute = GamesAlphabetRouteImport.update({
  id: '/games/alphabet',
  path: '/games/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cam': typeof CamRoute
  '/play': typeof PlayRoute
  '/tv': typeof TvRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/animals': typeof GamesAnimalsRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/freeze': typeof GamesFreezeRoute
  '/games/routine': typeof GamesRoutineRoute
  '/games/scavenger': typeof GamesScavengerRoute
  '/games/shapes': typeof GamesShapesRoute
  '/games/simon': typeof GamesSimonRoute
  '/games/yoga': typeof GamesYogaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cam': typeof CamRoute
  '/play': typeof PlayRoute
  '/tv': typeof TvRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/animals': typeof GamesAnimalsRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/freeze': typeof GamesFreezeRoute
  '/games/routine': typeof GamesRoutineRoute
  '/games/scavenger': typeof GamesScavengerRoute
  '/games/shapes': typeof GamesShapesRoute
  '/games/simon': typeof GamesSimonRoute
  '/games/yoga': typeof GamesYogaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cam': typeof CamRoute
  '/play': typeof PlayRoute
  '/tv': typeof TvRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/animals': typeof GamesAnimalsRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/freeze': typeof GamesFreezeRoute
  '/games/routine': typeof GamesRoutineRoute
  '/games/scavenger': typeof GamesScavengerRoute
  '/games/shapes': typeof GamesShapesRoute
  '/games/simon': typeof GamesSimonRoute
  '/games/yoga': typeof GamesYogaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cam'
    | '/play'
    | '/tv'
    | '/games/alphabet'
    | '/games/animals'
    | '/games/colors'
    | '/games/freeze'
    | '/games/routine'
    | '/games/scavenger'
    | '/games/shapes'
    | '/games/simon'
    | '/games/yoga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cam'
    | '/play'
    | '/tv'
    | '/games/alphabet'
    | '/games/animals'
    | '/games/colors'
    | '/games/freeze'
    | '/games/routine'
    | '/games/scavenger'
    | '/games/shapes'
    | '/games/simon'
    | '/games/yoga'
  id:
    | '__root__'
    | '/'
    | '/cam'
    | '/play'
    | '/tv'
    | '/games/alphabet'
    | '/games/animals'
    | '/games/colors'
    | '/games/freeze'
    | '/games/routine'
    | '/games/scavenger'
    | '/games/shapes'
    | '/games/simon'
    | '/games/yoga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CamRoute: typeof CamRoute
  PlayRoute: typeof PlayRoute
  TvRoute: typeof TvRoute
  GamesAlphabetRoute: typeof GamesAlphabetRoute
  GamesAnimalsRoute: typeof GamesAnimalsRoute
  GamesColorsRoute: typeof GamesColorsRoute
  GamesFreezeRoute: typeof GamesFreezeRoute
  GamesRoutineRoute: typeof GamesRoutineRoute
  GamesScavengerRoute: typeof GamesScavengerRoute
  GamesShapesRoute: typeof GamesShapesRoute
  GamesSimonRoute: typeof GamesSimonRoute
  GamesYogaRoute: typeof GamesYogaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cam': {
      id: '/cam'
      path: '/cam'
      fullPath: '/cam'
      preLoaderRoute: typeof CamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/yoga': {
      id: '/games/yoga'
      path: '/games/yoga'
      fullPath: '/games/yoga'
      preLoaderRoute: typeof GamesYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/simon': {
      id: '/games/simon'
      path: '/games/simon'
      fullPath: '/games/simon'
      preLoaderRoute: typeof GamesSimonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/shapes': {
      id: '/games/shapes'
      path: '/games/shapes'
      fullPath: '/games/shapes'
      preLoaderRoute: typeof GamesShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/scavenger': {
      id: '/games/scavenger'
      path: '/games/scavenger'
      fullPath: '/games/scavenger'
      preLoaderRoute: typeof GamesScavengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/routine': {
      id: '/games/routine'
      path: '/games/routine'
      fullPath: '/games/routine'
      preLoaderRoute: typeof GamesRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/freeze': {
      id: '/games/freeze'
      path: '/games/freeze'
      fullPath: '/games/freeze'
      preLoaderRoute: typeof GamesFreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/colors': {
      id: '/games/colors'
      path: '/games/colors'
      fullPath: '/games/colors'
      preLoaderRoute: typeof GamesColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/animals': {
      id: '/games/animals'
      path: '/games/animals'
      fullPath: '/games/animals'
      preLoaderRoute: typeof GamesAnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/alphabet': {
      id: '/games/alphabet'
      path: '/games/alphabet'
      fullPath: '/games/alphabet'
      preLoaderRoute: typeof GamesAlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CamRoute: CamRoute,
  PlayRoute: PlayRoute,
  TvRoute: TvRoute,
  GamesAlphabetRoute: GamesAlphabetRoute,
  GamesAnimalsRoute: GamesAnimalsRoute,
  GamesColorsRoute: GamesColorsRoute,
  GamesFreezeRoute: GamesFreezeRoute,
  GamesRoutineRoute: GamesRoutineRoute,
  GamesScavengerRoute: GamesScavengerRoute,
  GamesShapesRoute: GamesShapesRoute,
  GamesSimonRoute: GamesSimonRoute,
  GamesYogaRoute: GamesYogaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
