/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as PlayRouteImport } from './routes/play'
import { Route as CamRouteImport } from './routes/cam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesShapesRouteImport } from './routes/games.shapes'
import { Route as GamesColorsRouteImport } from './routes/games.colors'
import { Route as GamesAlphabetRouteImport } from './routes/games.alphabet'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const CamRoute = CamRouteImport.update({
  id: '/cam',
  path: '/cam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesShapesRoute = GamesShapesRouteImport.update({
  id: '/games/shapes',
  path: '/games/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesColorsRoute = GamesColorsRouteImport.update({
  id: '/games/colors',
  path: '/games/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAlphabetRoute = GamesAlphabetRouteImport.update({
  id: '/games/alphabet',
  path: '/games/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cam': typeof CamRoute
  '/play': typeof PlayRoute
  '/tv': typeof TvRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/shapes': typeof GamesShapesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cam': typeof CamRoute
  '/play': typeof PlayRoute
  '/tv': typeof TvRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/shapes': typeof GamesShapesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cam': typeof CamRoute
  '/play': typeof PlayRoute
  '/tv': typeof TvRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/shapes': typeof GamesShapesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cam'
    | '/play'
    | '/tv'
    | '/games/alphabet'
    | '/games/colors'
    | '/games/shapes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cam'
    | '/play'
    | '/tv'
    | '/games/alphabet'
    | '/games/colors'
    | '/games/shapes'
  id:
    | '__root__'
    | '/'
    | '/cam'
    | '/play'
    | '/tv'
    | '/games/alphabet'
    | '/games/colors'
    | '/games/shapes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CamRoute: typeof CamRoute
  PlayRoute: typeof PlayRoute
  TvRoute: typeof TvRoute
  GamesAlphabetRoute: typeof GamesAlphabetRoute
  GamesColorsRoute: typeof GamesColorsRoute
  GamesShapesRoute: typeof GamesShapesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cam': {
      id: '/cam'
      path: '/cam'
      fullPath: '/cam'
      preLoaderRoute: typeof CamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/shapes': {
      id: '/games/shapes'
      path: '/games/shapes'
      fullPath: '/games/shapes'
      preLoaderRoute: typeof GamesShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/colors': {
      id: '/games/colors'
      path: '/games/colors'
      fullPath: '/games/colors'
      preLoaderRoute: typeof GamesColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/alphabet': {
      id: '/games/alphabet'
      path: '/games/alphabet'
      fullPath: '/games/alphabet'
      preLoaderRoute: typeof GamesAlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CamRoute: CamRoute,
  PlayRoute: PlayRoute,
  TvRoute: TvRoute,
  GamesAlphabetRoute: GamesAlphabetRoute,
  GamesColorsRoute: GamesColorsRoute,
  GamesShapesRoute: GamesShapesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
