/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesShapesRouteImport } from './routes/games.shapes'
import { Route as GamesColorsRouteImport } from './routes/games.colors'
import { Route as GamesAlphabetRouteImport } from './routes/games.alphabet'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesShapesRoute = GamesShapesRouteImport.update({
  id: '/games/shapes',
  path: '/games/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesColorsRoute = GamesColorsRouteImport.update({
  id: '/games/colors',
  path: '/games/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAlphabetRoute = GamesAlphabetRouteImport.update({
  id: '/games/alphabet',
  path: '/games/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/shapes': typeof GamesShapesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/shapes': typeof GamesShapesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/games/alphabet': typeof GamesAlphabetRoute
  '/games/colors': typeof GamesColorsRoute
  '/games/shapes': typeof GamesShapesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play'
    | '/games/alphabet'
    | '/games/colors'
    | '/games/shapes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play' | '/games/alphabet' | '/games/colors' | '/games/shapes'
  id:
    | '__root__'
    | '/'
    | '/play'
    | '/games/alphabet'
    | '/games/colors'
    | '/games/shapes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayRoute: typeof PlayRoute
  GamesAlphabetRoute: typeof GamesAlphabetRoute
  GamesColorsRoute: typeof GamesColorsRoute
  GamesShapesRoute: typeof GamesShapesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/shapes': {
      id: '/games/shapes'
      path: '/games/shapes'
      fullPath: '/games/shapes'
      preLoaderRoute: typeof GamesShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/colors': {
      id: '/games/colors'
      path: '/games/colors'
      fullPath: '/games/colors'
      preLoaderRoute: typeof GamesColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/alphabet': {
      id: '/games/alphabet'
      path: '/games/alphabet'
      fullPath: '/games/alphabet'
      preLoaderRoute: typeof GamesAlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayRoute: PlayRoute,
  GamesAlphabetRoute: GamesAlphabetRoute,
  GamesColorsRoute: GamesColorsRoute,
  GamesShapesRoute: GamesShapesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
